# ~/.tmuxinator.yml (或者项目根目录下的 .tmuxinator.yml)

name: local_project  # 这个名字其实不重要，因为用 local 模式启动时会忽略它
root: .              # 设定为当前目录

# 启动时若需要自动依附到会话，设为 true (默认就是 true)
attach: true

windows:
  - main_workspace:
      # layout: tiled  # tiled 会自动把 4 个窗口平均分配成 田 字格
      # layout: b1da,360x80,0,0[360x68,0,0{125x68,0,0,14,234x68,126,0,15},360x11,0,69{186x11,0,69,16,173x11,187,69,17}]
      layout: 779f,194x58,0,0{148x58,0,0,29,45x58,149,0[45x44,149,0,30,45x13,149,45,31]}

      panes:
        # 1. 左上角
        - nvim .
        # 2. 右上角
        -
        # 3. 左下角 (留空即为普通终端)
        -